services:
  - type: web
    name: netflix-clone-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn mainprojectbck.wsgi:application
    autoDeploy: true
    envVars:
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "netflix-clone-backend-1-4ynr.onrender.com"
    postDeployCommand: python manage.py migrate
