# Generated by Django 5.2.7 on 2025-10-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('movie_no', models.IntegerField(primary_key=True, serialize=False)),
                ('movie_name', models.CharField(max_length=100)),
                ('movie_desc', models.CharField(max_length=100)),
                ('movie_rating', models.IntegerField()),
                ('movie_image', models.ImageField(upload_to='images/')),
                ('movie_video', models.FileField(upload_to='videos/')),
            ],
        ),
    ]
