# Generated by Django 5.2.7 on 2025-10-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='movie_desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movies',
            name='movie_image',
            field=models.ImageField(upload_to='movies/images/'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='movie_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='movies',
            name='movie_video',
            field=models.FileField(upload_to='movies/videos/'),
        ),
    ]
