# Generated by Django 5.2.5 on 2025-09-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='movie_rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='movies',
            name='movie_video',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
