# Generated by Django 5.2.5 on 2025-09-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_movies_movie_rating_alter_movies_movie_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='movie_video',
        ),
        migrations.AddField(
            model_name='movies',
            name='movie_video_url',
            field=models.URLField(null=True),
        ),
    ]
