# Generated by Django 5.2.7 on 2025-10-16 18:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_movies_movie_desc_alter_movies_movie_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='movie_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='movie_video',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='video'),
        ),
    ]
