# Generated by Django 5.2.5 on 2025-09-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_movies_movie_video_movies_movie_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='movie_video_url',
        ),
        migrations.AddField(
            model_name='movies',
            name='movie_video',
            field=models.FileField(default=1, upload_to='videos/'),
            preserve_default=False,
        ),
    ]
