# Generated by Django 5.2.7 on 2025-10-18 10:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_movies_movie_image_alter_movies_movie_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='movie_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='movie_video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video'),
        ),
    ]
