# Generated by Django 5.2.7 on 2025-10-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_movies_movie_image_alter_movies_movie_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='movie_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='movie_video',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
