# Generated by Django 5.2.5 on 2025-10-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_remove_movies_movie_video_url_movies_movie_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='movie_name',
            field=models.CharField(max_length=100),
        ),
    ]
